# Generated by Django 5.2.12 on 2026-04-05 12:31

import detection.models.media
import detection.models.report
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique file identifier', primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded media file', upload_to=detection.models.media.media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'avi', 'mov', 'mkv', 'webm', 'flv', 'wmv', 'jpg', 'jpeg', 'png', 'webp', 'bmp'))])),
                ('original_filename', models.CharField(help_text='Original filename as uploaded', max_length=500)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of file contents', max_length=64)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], db_index=True, help_text='Type of media (video/image)', max_length=10)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validated', 'Validated'), ('invalid', 'Invalid'), ('deleted', 'Deleted')], db_index=True, default='uploaded', help_text='File validation status', max_length=20)),
                ('validation_error', models.TextField(blank=True, help_text='Validation error message if invalid')),
                ('duration', models.FloatField(blank=True, help_text='Video duration in seconds', null=True)),
                ('frame_count', models.PositiveIntegerField(blank=True, help_text='Total number of frames', null=True)),
                ('fps', models.FloatField(blank=True, help_text='Frames per second', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Video/image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Video/image height in pixels', null=True)),
                ('codec', models.CharField(blank=True, help_text='Video codec used', max_length=50)),
                ('has_audio', models.BooleanField(default=False, help_text='Whether video contains audio track')),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to generated thumbnail', max_length=500)),
                ('preview_path', models.CharField(blank=True, help_text='Path to preview/compressed version', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Upload timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional file metadata')),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique analysis identifier', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current analysis status', max_length=20)),
                ('sequence_length', models.PositiveIntegerField(default=60, help_text='Number of frames to analyze')),
                ('model_used', models.CharField(blank=True, default='ensemble', help_text='ML model(s) used for analysis', max_length=100)),
                ('result', models.CharField(blank=True, choices=[('real', 'Real'), ('fake', 'Fake'), ('uncertain', 'Uncertain')], db_index=True, help_text='Detection result (real/fake/uncertain)', max_length=20, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence percentage (0-100)', null=True)),
                ('confidence_level', models.CharField(blank=True, help_text='Confidence category (low/medium/high/very_high)', max_length=20)),
                ('frames_analyzed', models.PositiveIntegerField(default=0, help_text='Number of frames actually analyzed')),
                ('faces_detected', models.PositiveIntegerField(default=0, help_text='Number of faces detected in video')),
                ('processing_time', models.FloatField(blank=True, help_text='Analysis duration in seconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed')),
                ('error_code', models.CharField(blank=True, help_text='Error code for failed analyses', max_length=20)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for async processing', max_length=255)),
                ('progress', models.FloatField(default=0.0, help_text='Processing progress (0-100)')),
                ('progress_message', models.CharField(blank=True, help_text='Current processing stage description', max_length=255)),
                ('webhook_url', models.URLField(blank=True, help_text='URL to notify when analysis completes')),
                ('webhook_sent', models.BooleanField(default=False, help_text='Whether webhook notification was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When analysis was submitted')),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When analysis completed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional analysis metadata')),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('media_file', models.ForeignKey(help_text='Associated video file', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='detection.mediafile')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique report identifier', primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('technical', 'Technical Report'), ('executive', 'Executive Summary')], default='summary', help_text='Type of report', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', help_text='Report file format', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Generated report file', null=True, upload_to=detection.models.report.report_upload_path)),
                ('file_size', models.BigIntegerField(default=0, help_text='Report file size in bytes')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Report content for JSON format')),
                ('is_public', models.BooleanField(default=False, help_text='Whether report is publicly accessible')),
                ('access_token', models.CharField(blank=True, db_index=True, help_text='Token for secure report access', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Report expiration timestamp', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times report was downloaded')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Last download timestamp', null=True)),
                ('generated_by', models.CharField(default='system', help_text='Who/what generated the report', max_length=100)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate report in seconds', null=True)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Options used during generation')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Report generation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('analysis', models.ForeignKey(help_text='Source analysis', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='detection.analysis')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Requester IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('referer', models.URLField(blank=True, help_text='Referring URL')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='detection.report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Download',
                'verbose_name_plural': 'Report Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_index', models.PositiveIntegerField(help_text='Frame position in video sequence')),
                ('timestamp_ms', models.FloatField(help_text='Frame timestamp in milliseconds')),
                ('prediction', models.CharField(help_text='Frame-level prediction', max_length=20)),
                ('confidence', models.FloatField(help_text='Frame-level confidence (0-100)')),
                ('face_detected', models.BooleanField(default=True, help_text='Whether a face was detected in this frame')),
                ('face_bbox', models.JSONField(blank=True, help_text='Face bounding box coordinates', null=True)),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to frame thumbnail', max_length=500)),
                ('heatmap_path', models.CharField(blank=True, help_text='Path to attention heatmap', max_length=500)),
                ('features', models.JSONField(blank=True, help_text='Extracted feature data', null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='detection.analysis')),
            ],
            options={
                'verbose_name': 'Analysis Frame',
                'verbose_name_plural': 'Analysis Frames',
                'ordering': ['analysis', 'frame_index'],
                'unique_together': {('analysis', 'frame_index')},
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['media_type', 'status'], name='detection_m_media_t_9cf27a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['user', 'created_at'], name='detection_m_user_id_7380a2_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_hash'], name='detection_m_file_ha_77ff81_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status', 'created_at'], name='detection_a_status_d5d4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['user', 'status'], name='detection_a_user_id_0f4e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['result', 'confidence'], name='detection_a_result_b1db80_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['analysis', 'format'], name='detection_r_analysi_02b492_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['access_token'], name='detection_r_access__0a9a54_idx'),
        ),
    ]
